apiVersion: v1
kind: Service
metadata:
  name: kafkaclient-external-service
  labels:
    app: kafkaclient
spec:
  type: NodePort
  selector:
    app: kafkaclient
  ports:
    - name: inbound
      protocol: TCP
      port: 8085
      targetPort: 8085
      nodePort: 30111
